# -*- coding: utf-8 -*-
"""BTP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hBb-QbNYXVCguZsWJWtkVumfrZ2mrsq5
"""



import time

while True:
    time.sleep(60)
    print("Keeping the runtime alive...")

from google.colab import drive
drive.mount('/content/drive')

import os
from glob import glob

# Replace with the actual path to your dataset in Google Drive
dataset_path_inside = '/content/drive/MyDrive/inside/images*/*'
dataset_path_outside = '/content/drive/MyDrive/outside/images*/*'


image_paths_inside = glob(dataset_path_inside)
image_paths_outside = glob(dataset_path_outside)

print(f"Number of images inside the folder: {len(image_paths_inside)}")
print(f"Number of images outside the folder: {len(image_paths_outside)}")

labels_path_inside = '/content/drive/MyDrive/inside/Annotations_XML/*.xml'
labels_path_outside = '/content/drive/MyDrive/outside/Annotations_XML/*.xml'

label_paths_inside = glob(labels_path_inside)
label_paths_outside = glob(labels_path_outside)

print(f"Number of label files inside the folder: {len(label_paths_inside)}")
print(f"Number of label files outside the folder: {len(label_paths_outside)}")

# !pip install Pillow

from PIL import Image

# Function to check the size of an image
def check_image_size(image_paths):
    for img_path in image_paths:
        with Image.open(img_path) as img:
            # Print the size of the image
            print(f"Image: {img_path}, Size: {img.size}")

# Check image sizes for inside and outside images
print("Inside Folder Image Sizes:")
check_image_size(image_paths_inside[:5])  # Check the first 5 images as a sample

print("\nOutside Folder Image Sizes:")
check_image_size(image_paths_outside[:5])  # Check the first 5 images as a sample

from PIL import Image
import matplotlib.pyplot as plt


def display_image(image_path):
    with Image.open(image_path) as img:

        plt.imshow(img)
        plt.axis('off')
        plt.show()


image_path = '/content/drive/MyDrive/inside/images/inside163.jpg'
display_image(image_path)

import multiprocessing

# Check the number of CPU cores
cpu_cores = multiprocessing.cpu_count()
print(f"Available CPU cores: {cpu_cores}")

from multiprocessing import Pool
from PIL import Image
import os


def resize_image(img_path_output):
    img_path, output_folder, size = img_path_output
    with Image.open(img_path) as img:

        img_resized = img.resize(size)
        img_name = os.path.basename(img_path)
        img_resized.save(os.path.join(output_folder, img_name))


def resize_images_multiprocessing(image_paths, output_folder, size=(320, 320), num_workers=2):
    if not os.path.exists(output_folder):
        os.makedirs(output_folder)


    img_args = [(img_path, output_folder, size) for img_path in image_paths]


    with Pool(num_workers) as p:
        p.map(resize_image, img_args)


resized_inside_folder = '/content/dataset/resized/inside'
resized_outside_folder = '/content/dataset/resized/outside'


resize_images_multiprocessing(image_paths_inside, resized_inside_folder, num_workers=4)
resize_images_multiprocessing(image_paths_outside, resized_outside_folder, num_workers=4)

print("Image resizing completed.")

from sklearn.model_selection import train_test_split
import os
import shutil

# List all image files in the resized inside and outside folders
image_files_inside = os.listdir(resized_inside_folder)
image_files_outside = os.listdir(resized_outside_folder)

# Label the image files to indicate their source (inside or outside)
image_files_inside = [(img, 'inside') for img in image_files_inside]
image_files_outside = [(img, 'outside') for img in image_files_outside]

# Combine the images from inside and outside
all_image_files = image_files_inside + image_files_outside

# Split into 70% train, 20% test, 10% validation
train_images, temp_images = train_test_split(all_image_files, test_size=0.3, random_state=42)
val_images, test_images = train_test_split(temp_images, test_size=0.67, random_state=42)  # 33% of 30% is 10%

# Create directories for train, test, and validation images and labels
os.makedirs('/content/dataset/images/train', exist_ok=True)
os.makedirs('/content/dataset/images/test', exist_ok=True)
os.makedirs('/content/dataset/images/val', exist_ok=True)
os.makedirs('/content/dataset/labels/train', exist_ok=True)
os.makedirs('/content/dataset/labels/test', exist_ok=True)
os.makedirs('/content/dataset/labels/val', exist_ok=True)

# Function to move images and corresponding labels
def move_files(image_list, inside_folder, outside_folder, target_image_folder, target_label_folder):
    for image, source_folder in image_list:
        if source_folder == 'inside':
            source_image_path = f'{inside_folder}/{image}'
        else:
            source_image_path = f'{outside_folder}/{image}'

        # Move the image
        shutil.move(source_image_path, target_image_folder)

        # Move the corresponding label
        label_file = image.replace('.jpg', '.txt')  # Assuming the image files are .jpg
        label_source_path = f'/content/dataset/labels/train/{label_file}'  # Adjust if needed

        if os.path.exists(label_source_path):
            shutil.move(label_source_path, target_label_folder)

# Move train images and labels
move_files(train_images, resized_inside_folder, resized_outside_folder, '/content/dataset/images/train', '/content/dataset/labels/train')

# Move test images and labels
move_files(test_images, resized_inside_folder, resized_outside_folder, '/content/dataset/images/test', '/content/dataset/labels/test')

# Move validation images and labels
move_files(val_images, resized_inside_folder, resized_outside_folder, '/content/dataset/images/val', '/content/dataset/labels/val')

print("Dataset successfully split into train, test, and validation sets.")

# !pip install ultralytics
# !pip install xmltodict



import xmltodict
import os
class_names = ['fire', 'smoke']

# Function to convert XML annotations to YOLO format
def convert_xml_to_yolo(xml_file, output_dir):
    with open(xml_file) as f:
        data = xmltodict.parse(f.read())

    image_width = int(data['annotation']['size']['width'])
    image_height = int(data['annotation']['size']['height'])

    objects = data['annotation'].get('object', [])
    if isinstance(objects, dict):
        objects = [objects]  # Handle the case where there's only one object in the XML

    yolo_lines = []
    for obj in objects:
        class_name = obj['name']
        if class_name not in class_names:
            continue  # Ignore objects not in our class list

        class_id = class_names.index(class_name)

        xmin = int(obj['bndbox']['xmin'])
        ymin = int(obj['bndbox']['ymin'])
        xmax = int(obj['bndbox']['xmax'])
        ymax = int(obj['bndbox']['ymax'])

        # Convert to YOLO format (normalized x_center, y_center, width, height)
        x_center = ((xmin + xmax) / 2) / image_width
        y_center = ((ymin + ymax) / 2) / image_height
        width = (xmax - xmin) / image_width
        height = (ymax - ymin) / image_height

        yolo_lines.append(f"{class_id} {x_center} {y_center} {width} {height}")

    # Write YOLO formatted labels to a .txt file
    output_file = os.path.join(output_dir, os.path.basename(xml_file).replace('.xml', '.txt'))
    with open(output_file, 'w') as out_f:
        out_f.write("\n".join(yolo_lines))

# Create directories to store the converted labels
os.makedirs('/content/dataset/labels/train', exist_ok=True)

# Convert all XML files inside the inside and outside folders
for xml_file in label_paths_inside:
    convert_xml_to_yolo(xml_file, '/content/dataset/labels/train')

for xml_file in label_paths_outside:
    convert_xml_to_yolo(xml_file, '/content/dataset/labels/train')

print("Conversion complete!")

import os


labels_path_val = '/content/drive/MyDrive/outside/Annotations_XML/*.xml'
label_paths_val = glob(labels_path_val)

# Directory to save the YOLO label files for the validation set
output_val_dir = '/content/dataset/labels/val'

# Make sure the directory exists
os.makedirs(output_val_dir, exist_ok=True)

# Re-run the XML-to-YOLO conversion for validation set
for xml_file in label_paths_val:
    convert_xml_to_yolo(xml_file, output_val_dir)

print("Label conversion complete for  outside validation set!")

import os
from glob import glob

# Path for the inside validation XML files
labels_path_val_inside = '/content/drive/MyDrive/inside/Annotations_XML/*.xml'

# Get all the XML files for the inside validation set
label_paths_val_inside = glob(labels_path_val_inside)

# Directory to save the YOLO label files for the validation set
output_val_dir = '/content/dataset/labels/val'

# Make sure the directory exists
os.makedirs(output_val_dir, exist_ok=True)

# Re-run the XML-to-YOLO conversion for the inside validation set
for xml_file in label_paths_val_inside:
    convert_xml_to_yolo(xml_file, output_val_dir)

print("Label conversion complete for inside validation set!")

import zipfile
import os

# Path to your uploaded zip file
zip_path = '/content/drive/MyDrive/dataset.zip'  # Or the path where you uploaded it

# Unzipping the file
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall('/content/FIRE_SMOKE_DATA')

# Define YAML configuration for YOLOv8
yaml_content = """
path: /content/FIRE_SMOKE_DATA  # Dataset root directory
train: images/train  # Train images (relative to 'path')
val: images/val  # Validation images (relative to 'path')
test: images/test  # Test images (optional)

nc: 2  # Number of classes (fire and smoke)
names: ['fire', 'smoke']  # Class names
"""

# Write the content to a YAML file
with open('/content/fire_smoke.yaml', 'w') as yaml_file:
    yaml_file.write(yaml_content)

print("YAML configuration file created!")

# !pip install ultralytics==8.0.20


from IPython import display
display.clear_output()

import ultralytics
ultralytics.checks()

# !wget https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8n.pt

# !pip install -U albumentations

# !yolo task=detect mode=train model=yolov8n.yaml data=/content/fire_smoke.yaml epochs=50 imgsz=640

# !yolo task=detect mode=val model=runs/detect/train/weights/best.pt data=/content/fire_smoke.yaml imgsz=640

# !yolo task=detect mode=predict model=runs/detect/train/weights/best.pt source=/content/FIRE_SMOKE_DATA/images/test/inside1005.jpg imgsz=320 save=True

from IPython.display import Image
Image(filename='runs/detect/predict/inside1005.jpg')  # Adjust the path if needed

import os
import random
from IPython.display import Image, display

# Define the test folder path
test_folder = '/content/FIRE_SMOKE_DATA/images/test'

# List all image files in the test folder
test_images = [f for f in os.listdir(test_folder) if f.endswith(('.jpg', '.jpeg', '.png'))]

# Randomly select 10 images
random_images = random.sample(test_images, 10)

# YOLOv8 prediction loop
for idx, img_name in enumerate(random_images, start=1):
    img_path = os.path.join(test_folder, img_name)

    # Run YOLOv8 prediction on the image
    # !yolo task=detect mode=predict model=runs/detect/train/weights/best.pt source={img_path} imgsz=320 save=True

    # Find the latest prediction folder
    prediction_folder = sorted([f for f in os.listdir('runs/detect') if f.startswith('predict')], key=lambda x: os.path.getmtime(f'runs/detect/{x}'))[-1]

    # Display the predicted image from the latest folder
    pred_img_path = f'runs/detect/{prediction_folder}/{img_name}'
    display(Image(filename=pred_img_path))

print("Predictions for 10 random test images have been made and displayed.")
